POST http://localhost:3000/users/crearusuario HTTP/1.1
Content-Type: application/json


//para agregar a la base de datos de usuarios
{
"nombre": "Erick ",
  "apellidos": "Vladimir",
  "ordenes": {
    "nombreProducto":" ",
    "Descripcion":" ",
    "precio":"0"}

}
### 

GET http://localhost:3000/users/usuarios HTTP/1.1
Content-Type: application/json


###


// crear categorias
POST http://localhost:3000/categorias/crearCategoria HTTP/1.1
Content-Type: application/json

{
  "nombreCategoria": "Mandaditos",
  "descripcion": ".",
  "color": "#8c649c",
  "icono": "fa fa-motorcycle",
   "empresas":[ {
                  "nombreEmpresa": "Rapi-Auto",
                  "imagen": "img/rapidito.png",
                  "producto": [{
                                "nombreProducto": "Encomienda",
                                "descripcion": ".",
                                "precio": 1149
                              },
                              {
                                "nombreProducto": "Taxi",
                                "descripcion": ".",
                                "precio": 4449
                              }
                              
                              ]
         
                },
                {
                  "nombreEmpresa": "RapiMoto",
                  "imagen": "img/rapidito.png",
                  "producto": [{
                                "nombreProducto": "MotoMami",
                                "descripcion": "Preferencial",
                                "precio": 349
                              },
                              {
                                "nombreProducto": "Motopapi",
                                "descripcion": ".",
                                "precio": 249
                              }
                              
                              ]
         
                }
   ]
            
        

}


###


// mostrar categorias

GET http://localhost:3000/categorias/categorias HTTP/1.1
Content-Type: application/json